### ISSUE TITLE
Trying spineps for vertebra segmentation

### ISSUE THREAD

**Issue by simonqueric** [ivadomed/lumbar-classification-rsna-challenge-2024#10]
[Spineps](https://github.com/Hendrik-code/spineps?tab=readme-ov-file) seems to be a good model to segment vertebra in the Sagittal images of RSNA-2024 dataset. 

Here is an example of a segmentation on a random image : 
![spineps](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/4276f3b6-9ce0-4fc2-8b95-ced508d40bf2)

- <b> Application in the case of our challenge : </b> if we follow a strategy "one model per condition and per level", it can be useful to select the desired level in the image and take it as an input, and to help the model to focus on vertebra-area.  

- ~~<b> Drawback </b> : Spineps is a line-command tool  on nifti files.~~

## Steps to reproduce

- Clone and install spineps following the [README](https://github.com/Hendrik-code/spineps/blob/main/README.md) instructions.
- Call the model on the serie `4003253/702807833`̀ with the line command `CUDA_VISIBLE_DEVICES=0 spineps sample -i /home/ge.polymtl.ca/p120616/sub-002_T2w.nii.gz -ms T2w_Segmentor_2.0 -mv Inst_Vertebra_3.0` and replace 0 in `CUDA_VISIBLE_DEVICES=0` with an available device.

**Comment by jcohenadad** [comment]
> Drawback : Spineps is a line-command tool on nifti files.

What is the issue with this?

**Comment by jcohenadad** [comment]
I would suggest trying on "difficult" cases, the segmentation quality will probably be lower. On the other hand, even if the quality is lower, there might be value in the segmentation (eg: to distinguish conditions, severity, and levels)

**Comment by simonqueric** [comment]
> > Drawback : Spineps is a line-command tool on nifti files.
> 
> What is the issue with this?

I might have made up a problem, because the imposed format of the challenge is dicom. I thought it was a possible issue for the submission. Nilser just showed me it was not a problem.

**Comment by jcohenadad** [comment]
> Nilser just showed me it was not a problem.

better to be fully specific in issues about the "what-and-how" for posterity-- eg: "It is possible to convert DICOM to NIfTI files using dcm2niix, and then process the NIfTI files using SPINEPS".

**Comment by simonqueric** [comment]
[Issue 27](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/issues/27) fixes this issue.
