### ISSUE TITLE
Aberrant instance number

### ISSUE THREAD

**Issue by simonqueric** [ivadomed/lumbar-classification-rsna-challenge-2024#15]
Some volumes contains slices with inconsistencies i.e  slices are not consecutive inside a given folder.
  
Here is the table with  subjects and volumes concerned (11 in total) with the number of jumps. 

![Capture d’écran du 2024-07-08 14-57-16](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/9ffc20d7-64da-4846-9483-b358ea679a8e)

- For the subject with study_id `2581283971`, it seems there are typos with slices named `5031.dcm`, `5039.dcm`, `5031.dcm`  whereas there are only 50 slices in the folder. see screenshot below : 

![Capture d’écran du 2024-07-08 16-07-51](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/e67cd40e-b0af-4455-8b8b-ff1f30125a05)

- For the subject with study_id `208289456`, serie_id `4140564625`, the volume only contains odd slices : 
![Capture d’écran du 2024-07-08 15-09-40](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/e9889443-e246-4931-b1df-a383b10ffbc5)

**Comment by jcohenadad** [comment]
> with the number of jumps

could you please clarify what you mean by that? I'm not sure I understand

**Comment by jcohenadad** [comment]
> For the subject with study_id 2581283971, it seems there are typos with a slice named 5031.dcm whereas there are only 50 slices in the folder. see screenshot below 

the screenshot has a lot of information, and it is unclear from that screenshot what actually supports the statement. For example, where do we see from that screenshot that there are only 50 slices? also, three subjects are shown in this screenshot. Also, the screenshot includes temporary comments from me (eg: "XXX (code)"), which adds to the confusion of this post.

**Comment by jcohenadad** [comment]
> For the subject with study_id 208289456, serie_id 4140564625, the volume only contains odd slices :

maybe the even slices are in another folder? What if you apply dcm2niix to the entire subject folder?

**Comment by simonqueric** [comment]
> > with the number of jumps
> 
> could you please clarify what you mean by that? I'm not sure I understand

The number of jumps is the number of times slices are missing between two dicoms. For instance, in the folder `208289456/4140564625` there are 14 such jumps (see the last bullet point of the top comment)

**Comment by simonqueric** [comment]
>> For the subject with study_id 208289456, serie_id 4140564625, the volume only contains odd slices :
> 
> maybe the even slices are in another folder? 

It wouldn't correspond to the structure of the dataset so I think this is not the case. 

>What if you apply dcm2niix to the entire subject folder?

I will check this point.

**Comment by simonqueric** [comment]
> > For the subject with study_id 2581283971, it seems there are typos with a slice named 5031.dcm whereas there are only 50 slices in the folder. see screenshot below
> 
> the screenshot has a lot of information, and it is unclear from that screenshot what actually supports the statement. For example, where do we see from that screenshot that there are only 50 slices? also, three subjects are shown in this screenshot. Also, the screenshot includes temporary comments from me (eg: "XXX (code)"), which adds to the confusion of this post.

I updated the screenshot so that it's clearer. Only one subject is shown, with three different slices with inconsistent names.

**Comment by jcohenadad** [comment]
if you open your DICOM images in a DICOM viewer (eg Horos) you will notice that the acquisition planes of the axial scans are not colinear, which means that each axial scan is an independently-ran sequence (ie: not a single volume, but multiple volumes), as illustrated below (see green slice angulation). So the concept of 'odd slices only' is not relevant.

![ezgif-4-63a10fc4fe](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/2482071/06c5e6e5-5a95-4376-9a84-a5e9043c0fd8)

This is already discussed in [this internal report (slide 10](https://docs.google.com/presentation/d/1wZON-R2CSZUc1dy09DNIpGcxfmnUvA0mzcsXbBL0RZo/edit#slide=id.g2ea6675a4be_0_5):

**Comment by jcohenadad** [comment]
> whereas there are only 50 slices in the folder. see screenshot below :

be careful. One DCM file does not necessarily mean one slice of a single volume. See e.g. https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/issues/15#issuecomment-2215188870

**Comment by simonqueric** [comment]
> > whereas there are only 50 slices in the folder. see screenshot below :
> 
> be careful. One DCM file does not necessarily mean one slice of a single volume. See e.g. [#15 (comment)](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/issues/15#issuecomment-2215188870)

Actually, I just checked : in the RSNA dataset, one dicom file <i>always</i> correspond to one slice of a volume. The scripts showing this is available in the notebook `stats.ipynb` in the part `Check if one dicom corresponds to one slice of a volume
`. I computed every shapes for each dicom, and it's always a tuple of length 2.

**Comment by jcohenadad** [comment]
> Actually, I just checked : in the RSNA dataset, one dicom file always correspond to one slice of a volume. The scripts showing this is available in the notebook stats.ipynb in the part Check if one dicom corresponds to one slice of a volume . I computed every shapes for each dicom, and it's always a tuple of length 2.

What I meant is: even though a DICOM file is a tuple of length 2, the question is: if you find two slices in a folder, do the two slices belong to a _single volume_ (ie: acquired with a single sequence), or to two different volumes (acquired with potentially different parameters, including, for example, orientation of the slice).
