### ISSUE TITLE
Trying a pretrained model for lumbar intervertebral disc degeneration

### ISSUE THREAD

**Issue by simonqueric** [ivadomed/lumbar-classification-rsna-challenge-2024#5]
A segmentation network for vertebral bodies / intervertebral disk was proposed in [Deep learning-based high-accuracy quantitation for lumbar intervertebral disc degeneration from MRI](https://www.nature.com/articles/s41467-022-28387-5). This segmentation is supposed to work on T2W sagittal images. 

Bellow, an example of segmentation with author's dataset : 

![img](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/89afdf88-1655-4b35-b197-5d5db97c4b71)

However, if fails dramatically on the rsna-2024 dataset : 

![2](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/assets/56970073/d786decf-aa7d-4bb1-a3c9-87fc3444345f)

It's probably not worth trying to use it.

**Comment by jcohenadad** [comment]
Wow, I'm surprising about the low quality of the prediction, given how similar the two contrasts look like. I'm sure @NathanMolinier would have useful feedback

**Comment by jcohenadad** [comment]
@simonqueric please always attach and/or point to the code you used to run the model (for reproducibility and transparency purpose)

**Comment by NathanMolinier** [comment]
I would be curious to know how different is the left-right (LR) resolution between the two images.

I you want a better spine segmentations network, [spineps](https://github.com/Hendrik-code/spineps) is so far one of the most promising.

**Comment by simonqueric** [comment]
[Issue 27](https://github.com/ivadomed/lumbar-classification-rsna-challenge-2024/issues/27) solves the challenge raised by the issue.
